on:
  push:
    branches: -master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ssh.manifestwebsites.com
          username: Dickies
          password: LilYellowCup
          # server-dir: /public-html/production.manifestwebsites.com
